version: 2.1

parameters:
  manifest-url:
    type: string
    default: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp"
  manifest-branch:
    type: string
    default: "twrp-12.1"
  vendor-name:
    type: string
    default: "samsung"
  device-name:
    type: string
    default: "a12s"
  target:
    type: string
    default: "recoveryimage"
  build-type:
    type: string
    default: "eng"

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large

    steps:
      - run:
          name: Setup build environment
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update -y
            sudo apt install -y \
              tree \
              gperf \
              gcc-multilib \
              gcc-10-multilib \
              g++-multilib \
              g++-10-multilib \
              ccache \
              libc6-dev \
              lib32ncurses5-dev \
              x11proto-core-dev \
              libx11-dev \
              tree \
              lib32z-dev \
              libgl1-mesa-dev \
              libxml2-utils \
              xsltproc \
              bc \
              openjdk-8-jdk \
              lib32readline-dev \
              lib32z1-dev \
              liblz4-tool \
              libncurses5-dev \
              libncurses5 \
              libtinfo5 \
              libsdl1.2-dev \
              libwxgtk3.0-gtk3-dev \
              libxml2 \
              linux-modules-extra-$(uname -r) \
              lzop \
              pngcrush \
              schedtool \
              squashfs-tools \
              imagemagick \
              libbz2-dev \
              lzma \
              ncftp \
              qemu-user-static \
              libstdc++-10-dev \
              python2 \
              python3 \
              repo \
              linux-modules-extra-$(uname -r)
            sudo ln -s /usr/bin/python2 /usr/bin/python
            
      - run:
          name: Prepare system
          command: |            
            sudo dd if=/dev/zero of=/swapfile bs=12MB count=1024
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile

            sudo modprobe zram
            sudo zramctl /dev/zram0 --algorithm zstd --size 56G
            sudo mkswap /dev/zram0
            sudo swapon --priority 150 /dev/zram0
            
            sudo sysctl vm.swappiness=180
            sudo sysctl vm.watermark_boost_factor=0
            sudo sysctl vm.watermark_scale_factor=125
            sudo sysctl vm.page-cluster=0

      - run:
          name: Fetch sources
          command: |
            git config --global user.name "Ahmed Shahir"
            git config --global user.email "ashahir-build-circleci@xyz.pqr"
            git config --global color.ui true

            git clone 

            cd ${CIRCLE_WORKING_DIRECTORY}

            repo init --depth=1 -u << pipeline.parameters.manifest-url >> -b << pipeline.parameters.manifest-branch >>
            repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune            

      - run:
          name: Build
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            
            set +e
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            set -e

            lunch twrp_<< pipeline.parameters.device-name >>-<< pipeline.parameters.build-type >> && make clean && mka adbd << pipeline.parameters.target >>

      - store_artifacts:
          path: out/target/product/

      - run:
          name: Debug
          when: on_fail
          command: tree -L 4 ${CIRCLE_WORKING_DIRECTORY}

workflows:
  build-recovery:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
      - publish:
          requires:
            - build
